name: Deploy React App to GitHub Pages (User Page)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }} # 카카오 API 키
          REACT_APP_PUBLIC_KEY: ${{ secrets.REACT_APP_PUBLIC_KEY }} # (이메일 관련 키로 추정)
          REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }} # (이메일 관련 ID로 추정)
          REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID }} # (이메일 관련 템플릿 ID로 추정)
          # 사용자 페이지 (username.github.io)는 루트에서 서빙되므로,
          # package.json의 homepage를 설정하지 않거나 "." 또는 "/" 로 설정하는 것이 일반적입니다.
          # Create React App 기준: package.json 에 "homepage": "." 추가 또는 제거 후 빌드
        run: npm run build # React 앱 빌드 명령어 (기본: build 폴더에 생성)

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # React 앱의 빌드 결과물이 생성되는 폴더를 지정합니다. (대부분 'build')
          path: ./build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4