name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 기록 가져오기

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install react@18.3.1 react-dom@18.3.1 react-kakao-maps-sdk@1.1.27

      - name: Build React app
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: build
          clean: true